version: "3.9"
services: 
  backend:
    container_name: ng_backend
    build: ./
    ports: 
      - 3301:3301
    working_dir: /app-backend
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306  
  db:
    image: mysql:8.0.21
    container_name: db   
    platform: linux/x86
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
